name: Deploy Website

on: workflow_dispatch

jobs:
  build:
    env:
      PORT: '8089'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy website
        run: |
          pwd
          sshpass -p 'nokiaaclabs' ssh -o StrictHostKeyChecking=no ec2-user@54.147.46.24 "rm -rf /home/ec2-user/${{env.PORT}}"
          sshpass -p "nokiaaclabs" scp -o StrictHostKeyChecking=no -r /home/runner/work/Nokia-CI-CD/Nokia-CI-CD ec2-user@54.147.46.24:/home/ec2-user/${{env.PORT}}
          sshpass -p 'nokiaaclabs' ssh -o StrictHostKeyChecking=no ec2-user@54.147.46.24 "sudo docker rm nginx-${{env.PORT}} --force || true"
          sshpass -p 'nokiaaclabs' ssh -o StrictHostKeyChecking=no ec2-user@54.147.46.24 "sudo docker run -d -v /home/ec2-user/${{env.PORT}}:/usr/share/nginx/html:ro --name nginx-${{env.PORT}} -p ${{env.PORT}}:80 nginx"
